{{ if .Values.mesh.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cluster }}-mesh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{ end }}