---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.cluster }}-svc-acc
  labels:
    app: traefikee
    release: {{ .Values.cluster }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cluster }}-svc-acc-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cluster }}-svc-acc
    namespace: {{ .Release.Namespace }}
