---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.cluster }}-svc-acc-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ .Values.cluster }}-svc-acc-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cluster }}-svc-acc
    namespace: {{ .Release.Namespace }}
