# Default values for Traefik EE
cluster: "default"

proxy:
  image:
    name: traefik/traefikee
    # defaults to appVersion
    tag: ""
    pullPolicy: IfNotPresent
  proxies: 2
  controllers: 1
  staticConfig:
    enabled: false
    file: "static.yaml"
  ports:
    - containerPort: 443
      name: https
    - containerPort: 80
      name: http

mesh:
  enabled: true
  kubedns: false
  clusterDomain: "cluster.local"
