# Default values for Traefik EE
cluster: "default"

proxy:
  image:
    name: traefik/traefikee
    # defaults to appVersion
    tag: ""
    pullPolicy: IfNotPresent
  proxies: 2
  controllers: 1
  installCRDs: true
  # TODO: withoutresources
  staticConfig:
    enabled: true
    file: "static.yaml"

traefik-mesh:
  enabled: false
  # kubedns: true
  # clusterDomain: cluster.local
  # proxy:
  #   image:
  #     name: traefik/traefikee
  #     tag: "v2.5.0"
  #     pullPolicy: IfNotPresent
