# Default values for Traefik EE
cluster: "default"

proxy:
  image:
    name: traefikee
    repository: traefik
    # defaults to appVersion
    tag: ""
    pullPolicy: IfNotPresent
  proxies: 2
  controllers: 1
  installCRDs: true
  staticConfig:
    enabled: true
    file: "static.yaml"

mesh:
  enabled: true
