# Default values for Traefik EE
cluster: "default"

proxy:
  image:
    name: traefik/traefikee
    # defaults to appVersion
    tag: ""
    pullPolicy: IfNotPresent
  proxies: 2
  controllers: 1
  staticConfig:
    enabled: true
    file: "static.yaml"

mesh:
  enabled: false
  kubedns: false
  clusterDomain: "cluster.local"
