---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cluster }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: traefikee
      release: {{ .Values.cluster }}
      component: controllers
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cluster }}-ctrl-svc
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        app: traefikee
        release: {{ .Values.cluster }}
        component: controllers
    spec:
      serviceAccountName: {{ .Values.cluster }}-svc-acc
{{ if .Values.controller.affinity }}
      affinity:
{{ toYaml .Values.controller.affinity | indent 8 }}
{{ end }}
{{ if .Values.controller.tolerations }}
      tolerations:
{{ toYaml .Values.controller.tolerations | indent 8 }}
{{ end }}
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-dns
          image: busybox:1.31.1
          command: ['sh', '-c', 'until nslookup -type=a {{ printf "%s-ctrl-svc.%s" .Values.cluster .Release.Namespace }}.svc.cluster.local; do echo waiting for published dns records; sleep 1; done;']
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "1000m"
      containers:
        - name: {{ .Values.cluster }}-controller
          image: {{ template "traefikee-helm-chart.image-name" . }}
          imagePullPolicy: {{ .Values.controller.containers.controller.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cluster }}-license
                  key: license
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          ports:
            - containerPort: 4242
              name: control-port
            - containerPort: 8080
              name: api
          readinessProbe:
            tcpSocket:
              port: control-port
            initialDelaySeconds: 10
            periodSeconds: 5
{{ if .Values.controller.containers.controller.resources }}
          resources:
{{ toYaml .Values.controller.containers.controller.resources | indent 12 }}
{{ end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/traefikee
            - name: sockets
              mountPath: /var/run/traefikee
            {{ if (.Values.controller.containers.controller.staticConfig).configMap }}
            - name: staticconfig
              mountPath: /var/run/traefikee/config
            {{ end }}
          command:
            - "/traefikee"
            - "controller"
            - "--name=$(POD_NAME)"
            - "--advertise=$(POD_NAME).{{ .Values.cluster }}-ctrl-svc.$(POD_NAMESPACE):4242"
            - "--discovery.dns.bootstrapexpected={{ .Values.controller.replicas }}"
            - "--discovery.dns.domain={{ .Values.cluster }}-ctrl-svc.$(POD_NAMESPACE)"
            - "--jointoken.kubernetes.prefix={{ .Values.cluster }}"
            - "--jointoken.kubernetes.namespace={{ .Release.Namespace }}"
            - "--license=$(LICENSE)"
            - "--api.autocerts"
            {{ if (.Values.controller.containers.controller.staticConfig).configMap }}
            - "--configFile=/var/run/traefikee/config/{{ .Values.controller.containers.controller.staticConfig.configMapKey }}"
            {{ end }}
            - "--log.level="
            - "--log.filepath="
            - "--log.format="
            - "--plugin.url=https://{{ .Values.cluster }}-plugin-registry-svc.{{ .Release.Namespace }}.svc.cluster.local"
            - "--plugin.token={{ or (include "token" .) (.Values.global.registry_token) }}"
      volumes:
        - name: sockets
          emptyDir: {}
        {{ if (.Values.controller.containers.controller.staticConfig).configMap }}
        - name: staticconfig
          configMap:
            name: {{ .Values.controller.containers.controller.staticConfig.configMap }}
        {{ end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cluster }}-plugin-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
    release: {{ .Values.cluster }}
spec:
  serviceName: {{ .Values.cluster }}-plugin-registry-svc
  replicas: {{ .Values.registry.replicas }}
  selector:
    matchLabels:
      app: traefikee
      release: {{ .Values.cluster }}
      component: registry
  template:
    metadata:
      labels:
        app: traefikee
        release: {{ .Values.cluster }}
        component: registry
    spec:
{{ if .Values.registry.affinity }}
      affinity:
{{ toYaml .Values.registry.affinity | indent 8 }}
{{ end }}
{{ if .Values.registry.tolerations }}
      tolerations:
{{ toYaml .Values.registry.tolerations | indent 8 }}
{{ end }}
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      initContainers:
        - name: wait-dns
          image: busybox:1.31.1
          command: ['sh', '-c', 'until nslookup -type=a {{ printf "%s-ctrl-svc.%s" .Values.cluster .Release.Namespace }}.svc.cluster.local; do echo waiting for published dns records; sleep 1; done;']
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "1000m"
      containers:
        - name: {{ .Values.cluster }}-plugin-registry
          image: {{ template "traefikee-helm-chart.image-name" . }}
          imagePullPolicy: {{ .Values.registry.containers.registry.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          # readinessProbe:
          #   tcpSocket:
          #     port: http
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
{{ if .Values.registry.containers.registry.resources }}
          resources:
{{ toYaml .Values.registry.containers.registry.resources | indent 12 }}
{{ end }}
          volumeMounts:
            - name: {{ .Values.cluster }}-plugin-registry-data
              mountPath: "/var/lib/traefikee"
            - name: plugin-data
              mountPath: "/var/lib/plugins"
            - name: "join-token"
              mountPath: "/var/run/secrets"
          command:
            - "/traefikee"
            - "plugin-registry"
            - "--name=$(POD_NAME)"
            - "--plugindir=/var/lib/plugins"
            - "--token={{ or (include "token" .) (.Values.global.registry_token) }}"
            - "--discovery.dns.domain={{ .Values.cluster }}-ctrl-svc.$(POD_NAMESPACE)"
            - "--jointoken.file.path=/var/run/secrets"
            - "--log.level="
            - "--log.filepath="
            - "--log.format="
      volumes:
        - name: {{ .Values.cluster }}-plugin-registry-data
          emptyDir: {}
        - name: "join-token"
          secret:
            secretName: {{ .Values.cluster }}-tokens
  volumeClaimTemplates:
    - metadata:
        name: plugin-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
