---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-plugin-registry-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
    {{- with (.Values.registry).serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with (.Values.registry).serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: traefikee
    release: {{ .Values.cluster }}
    component: registry
