---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-plugin-registry-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: traefikee
    release: {{ .Release.Name }}
    component: registry
