{{- $proxies := dict "proxy" .Values.proxy }}
{{- $proxies = merge $proxies .Values.additionalProxies }}
{{- range $proxyName, $proxy := $proxies }}

{{- if $proxy.autoscaling.enabled }}

{{- if not $proxy.autoscaling.maxReplicas }}
  {{- fail "ERROR: maxReplicas is required on HPA" }}
{{- end }}

{{- if semverCompare ">=1.23.0-0" $.Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.cluster }}-{{ $proxyName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "common.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.cluster }}-{{ $proxyName }}
{{- with $proxy.autoscaling.minReplicas }}
  minReplicas: {{ . }}
{{- end }}
  maxReplicas: {{ $proxy.autoscaling.maxReplicas }}
{{- with $proxy.autoscaling.metrics }}
  metrics:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $proxy.autoscaling.behavior }}
  behavior:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
