{{- $proxies := dict "proxy" .Values.proxy }}
{{- $proxies = merge $proxies .Values.additionalProxies }}
{{- range $proxyName, $proxy := $proxies }}

{{ if $proxy.podDisruptionBudget }}
---
{{- if semverCompare "<1.21.0-0" $.Capabilities.KubeVersion.Version }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ $.Values.cluster }}-{{ $proxyName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  {{- with $proxy.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- else }}
  maxUnavailable: {{ $proxy.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: traefikee
      component: proxies
      release: {{ $.Values.cluster }}
{{- end }}

{{- end }}
