{{- if .Values.proxyInternal }}
{{ if .Values.proxyInternal.podDisruptionBudget }}
---
{{- if semverCompare "<=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1beta1
{{- else -}}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.cluster }}-proxyInternal
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  {{ if .Values.proxyInternal.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.proxyInternal.podDisruptionBudget.minAvailable }}
  {{ else }}
  maxUnavailable: {{ .Values.proxyInternal.podDisruptionBudget.maxUnavailable | default 1 }}
  {{ end }}
  selector:
    matchLabels:
      app: traefikee
      component: proxies-internal
      release: {{ .Values.cluster }}
{{ end }}
{{- end }}
