---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-proxy-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: traefikee
    release: {{ .Release.Name }}
    component: proxies
