---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-proxy-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
{{ toYaml .Values.proxy.ports | indent 4}}

  selector:
    app: traefikee
    release: {{ .Release.Name }}
    component: proxies
