---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-proxy-svc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
{{- if .Values.proxy.service }}
{{ toYaml .Values.proxy.service | indent 2 }}
{{- else }}
  type: LoadBalancer
  ports:
{{ toYaml .Values.proxy.containers.proxy.ports | indent 4}}
{{- end }}
  selector:
    app: traefikee
    release: {{ .Values.cluster }}
    component: proxies
