---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-proxy-svc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.proxy.serviceType | default "LoadBalancer"}}
  ports:
{{ toYaml .Values.proxy.ports | indent 4 }}
  selector:
    app: traefikee
    release: {{ .Values.cluster }}
    component: proxies
