{{- $proxies := dict "proxy" .Values.proxy }}
{{- $proxies = merge $proxies .Values.additionalProxies }}
{{- range $proxyName, $proxy := $proxies }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.cluster }}-{{ $proxyName }}-svc
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    component: {{ (eq (len $proxies) 1) | ternary "proxies" $proxyName }}
    {{- with ($proxy).serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with ($proxy).serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $proxy.serviceType | default "LoadBalancer" }}
  ports: {{ toYaml $proxy.servicePorts | nindent 4 }}
  {{- with $proxy.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $proxy.externalIPs }}
  externalIPs: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with $proxy.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $proxy.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $proxy.ipFamilies }}
  ipFamilies: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with $proxy.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with $proxy.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $proxy.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml . | nindent 2 }}
  {{- end }}

  selector:
    app: traefikee
    release: {{ $.Values.cluster }}
    component: {{ (eq (len $proxies) 1) | ternary "proxies" $proxyName }}
{{- end }}
