---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-proxy-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
    {{- with (.Values.proxy).serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with (.Values.proxy).serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.proxy.serviceType | default "LoadBalancer" }}
  ports: {{ toYaml .Values.proxy.servicePorts | nindent 4 }}
  {{- if .Values.proxy.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.loadBalancerIP }}
  {{- end }}
  selector:
    app: traefikee
    release: {{ .Values.cluster }}
    component: proxies
