{{ if and .Values.mesh.enabled .Values.mesh.kubedns}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    {{ include "common.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: traefikee-coredns-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefikee-coredns
subjects:
  - kind: ServiceAccount
    name: mesh-coredns
    namespace: {{ .Release.Namespace }}
{{ end }}
