{{ if and .Values.mesh.enabled .Values.mesh.kubedns}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mesh-coredns
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
    release: {{ .Values.cluster }}
{{ end }}