---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-ctrl-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with (.Values.controller).serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with (.Values.controller).serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: traefikee
    component: controllers
    release: {{ .Values.cluster }}
  clusterIP: None
  publishNotReadyAddresses: true
