---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-ctrl-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefikee
spec:
  selector:
    app: traefikee
    component: controllers
  clusterIP: None
